config/routes.rb
Glow::Application.routes.draw do
  resources :incubators
  root :to => 'incubators#index'
  

end

app/models/incubator.rb
class Incubator < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/incubators_controller.rb
class IncubatorsController < ApplicationController
  # GET /incubators
  # GET /incubators.json
  def index
    @incubators = Incubator.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @incubators }
    end
  end

  # GET /incubators/1
  # GET /incubators/1.json
  def show
    @incubator = Incubator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @incubator }
    end
  end

  # GET /incubators/new
  # GET /incubators/new.json
  def new
    @incubator = Incubator.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @incubator }
    end
  end

  # GET /incubators/1/edit
  def edit
    @incubator = Incubator.find(params[:id])
  end

  # POST /incubators
  # POST /incubators.json
  def create
    @incubator = Incubator.new(params[:incubator])

    respond_to do |format|
      if @incubator.save
        format.html { redirect_to @incubator, notice: 'Incubator was successfully created.' }
        format.json { render json: @incubator, status: :created, location: @incubator }
      else
        format.html { render action: "new" }
        format.json { render json: @incubator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /incubators/1
  # PUT /incubators/1.json
  def update
    @incubator = Incubator.find(params[:id])

    respond_to do |format|
      if @incubator.update_attributes(params[:incubator])
        format.html { redirect_to @incubator, notice: 'Incubator was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @incubator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incubators/1
  # DELETE /incubators/1.json
  def destroy
    @incubator = Incubator.find(params[:id])
    @incubator.destroy

    respond_to do |format|
      format.html { redirect_to incubators_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incubators_helper.rb
module IncubatorsHelper
end

app/views/incubators/_form.html.erb
<%= form_for(@incubator) do |f| %>
  <% if @incubator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incubator.errors.count, "error") %> prohibited this incubator from being saved:</h2>

      <ul>
      <% @incubator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :avg_investment %><br />
    <%= f.text_field :avg_investment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incubators/_incubator.html.haml
.incubator
	<img class="thumbnail" src="http://placehold.it/210x150" alt="">
	%p
		= "#{incubator.name}"
		%span 
			= "#{incubator.city}, #{incubator.state}"

app/views/incubators/edit.html.erb
<h1>Editing incubator</h1>

<%= render 'form' %>

<%= link_to 'Show', @incubator %> |
<%= link_to 'Back', incubators_path %>

app/views/incubators/index.html.erb
<h1>Listing incubators</h1>

<%= render  @incubators %>

<%= link_to 'New Incubator', new_incubator_path %>

app/views/incubators/index.html.haml
%h1
	Incubators

= render  @incubators

= link_to 'New Incubator', new_incubator_path

app/views/incubators/new.html.erb
<h1>New incubator</h1>

<%= render 'form' %>

<%= link_to 'Back', incubators_path %>

app/views/incubators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @incubator.name %>
</p>

<p>
  <b>Street:</b>
  <%= @incubator.street %>
</p>

<p>
  <b>City:</b>
  <%= @incubator.city %>
</p>

<p>
  <b>State:</b>
  <%= @incubator.state %>
</p>

<p>
  <b>Website:</b>
  <%= @incubator.website %>
</p>

<p>
  <b>Body:</b>
  <%= @incubator.body %>
</p>

<p>
  <b>Avg investment:</b>
  <%= @incubator.avg_investment %>
</p>


<%= link_to 'Edit', edit_incubator_path(@incubator) %> |
<%= link_to 'Back', incubators_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Glow</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title
			Glow
		= stylesheet_link_tag    "application"
		= javascript_include_tag "application"
		= csrf_meta_tags

	%body
		= yield